[package]
name = "rust-by-bot"
version = "0.1.0"
authors = ["Ihar Novik <nolik03@godeltech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = "0.7.0"